app/__init__.py
import os
from flask import Flask

def create_app():
    app = Flask(__name__)
    
    # Set the secret key. Consider adding it to a .env file or your environment variables
    app.secret_key = os.getenv('SECRET_KEY', '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')

    # Ensure you don't use 'your_default_secret_key_here' in production
    from .routes import main as main_routes
    app.register_blueprint(main_routes)

    return app

app/routes.py
from flask import current_app, Blueprint, render_template, request, url_for
from werkzeug.utils import secure_filename
import os
from .inference import run_inference
from flask import request, jsonify
from .rag_model import get_animal_info
from flask import session
from .rag_model import generate_chat_response

main = Blueprint('main', __name__)

# Here we define the main route to the application 
@main.route('/')
def home():
    """
    Purpose: Render the main page of the application
    """
    return render_template('index.html')

# Here we define another route to upload an image
@main.route('/upload', methods=['POST'])
def upload_image():
    """
    Purpose: Upload an image, run inference, and display the results
    """
    # Check if an image was uploaded
    if 'image' in request.files:
        image = request.files['image']
        if image.filename != '':
            # Here we secure the filename to prevent any malicious attacks
            filename = secure_filename(image.filename)
            # Here we save the image to the static directory
            filepath = os.path.join(current_app.root_path, 'static/images', filename)
            image.save(filepath)

            # We open the file and then read the image bytes
            with open(filepath, 'rb') as file:
                image_bytes = file.read()
                # We use the run_inference function to get the output image and detected classes
                # This function is defined in the 
                output_image_bytes, detected_classes = run_inference(image_bytes)
            
            # Here we save the processed image to the static directory
            output_filename = f"processed_{filename}"
            output_path = os.path.join(current_app.root_path, 'static/images', output_filename)
            with open(output_path, 'wb') as f:
                f.write(output_image_bytes)
            
            # Get URL for the processed image
            image_url = url_for('static', filename=f'images/{output_filename}')
            
            # Render results template
            return render_template('results.html', image_url=image_url, detected_classes=detected_classes)
    # If the image is not a wildlife animal that falls within the categories, we return an error. 
    return 'No image uploaded', 400

# Here we create a route to get information about the detected animal
@main.route('/get-animal-info', methods=['POST'])
def animal_info():
    """
    Purpose: Get information about the detected animal
    """
    data = request.json
    # Here we get the detected class from the request data
    detected_class = data.get('animal_name')
    # If there is a detected class, we use the get_animal_info function to get information about the animal
    # The get_animal_info function is defined in the rag_model.py file
    if detected_class:
        info = get_animal_info(detected_class)
        return jsonify(info=info)
    else:
        return jsonify({'error': 'No animal class provided'}), 400

# Here we create a route to chat with the chatbot 
@main.route('/chat', methods=['POST'])
def chat():
    """
    # Purpose: Chat with the chatbot
    """
    data = request.json
    message = data.get('message', '')

    if 'conversation' not in session:
        session['conversation'] = []

    # We can define the role of the user and the content of the message
    session['conversation'].append({'role': 'user', 'content': message})
    # The generate chat response function is defined in the rag_model.py file
    response_message = generate_chat_response(session['conversation'])
    session['conversation'].append({'role': 'assistant', 'content': response_message})
    # Here we return the response message
    return jsonify({'message': response_message})

app/templates/index.html
<!-- app/templates/index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Image</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
        }
        .upload-form {
            margin-bottom: 20px;
        }
        .submit-button {
            cursor: pointer;
        }
    </style>
</head>
<body>
    <header class="header-background">
        <div class="container">
            <h1>Habitat Hero!</h1>
        </div>
    </header>
    <div class="upload-form">
        <form action="/upload" method="post" enctype="multipart/form-data">
            <div class="file-upload-container"> 
                <input type="file" name="image" required>
                <input type="submit" value="Upload" class="submit-button">
            </div>
        </form>
    </div>
    <div class="horizontal-info-boxes">
        <div class="about-box">
            <h2>Instructions for Application</h2>
            1. Upload an image of a wildlife animal using the "Choose File" button. This can either be a single animal or a group of animals.<br>
            2. Click the "Upload" button to submit the image.<br>
            3. You will be redirected to another page where the application will display the name(s) of the detected animal(s) in the image as well as the original image with bounding boxes around the animals in the image.<br>
            4. Click on the name of a detected animal to garner more general information about the animal as well as its endangered status.<br>
            5. Ask the chatbot questions to learn more about the animal, its habitat, conservation status, and ways we as humans can help.
            <br><br>
            <h2>Methodologies Used</h2>
            1. The application uses a fine-tuned YOLOv5 object detection model to detect wildlife animals in images that the user uploads.<br>
            2. Relevant chunks of information regarding the detected animals are extracted from the MongoDB Atlas database for RAG purposes and prompt-engineering.<br>
            3. The relevant chunks are then passed as context to OpenAI's GPT-3.5 Turbo to generate information to the user regarding the animal of focus.<br>
        </div>
        <div class="purpose-box">
            <h2>Purpose</h2>
            On a global level, there are unfortunately many commonly known species such as elephants, rhinos, gorillas, etc. that are now 
            endangered and face extinction due to a lack of public awareness and conservation engagement. Although there are tools in place to 
            help mitigate the chance of extinction of these endangered species, there is a severe lack of educational tools that give the public a 
            broader understanding of the problem as well as potential solutions. This project helps bridge this gap by allowing the public to learn 
            more about a wide variety of wild-life animals and potential ways we as humans can help animals around the world thrive. 
            The wildlife animals that the model primarily focuses on are: antelope, bat, bear, bee, butterfly, Domestic short-haired cats, chimpanzee, 
            coyote, dolphin, eagle, elephant, gorilla, hippopotamus, rhinoceros, hummingbird, kangaroo, koala, leopard, lion, lizard, orangutan, panda,
            penguin, seal, shark, tiger, turtle, whale, and zebra. <br><br>
            The concept of using computer vision to identify or classify animals is not inherently novel. There have been research papers in the past 
            that have attempted to utilize computer vision for animal detection. For example, “The iNaturalist Species Classification and Detection Dataset”
            by Grant Van Horn et al. is a groundbreaking research paper that focuses on classification of different species via a large dataset of animals.
            Feel free to check out the paper to learn more about interesting CV methods being used in the field of wildlife conservation.
        </div>
        <div class="resources-box">
            <h2>Additional Resources</h2>
            Here are some additional resources that can be used to learn more about wildlife conservation and how you can help:<br><br>
            World Wildlife Fund: "WWF works to help local communities conserve the natural resources they depend upon; transform markets and policies toward sustainability; and protect and restore species and their habitats. Our efforts ensure that the value of nature is reflected in decision-making from a local to a global scale.
            WWF connects cutting-edge conservation science with the collective power of our partners in the field, more than one million supporters in the United States and five million globally, as well as partnerships with communities, companies, and governments. Today, human activities put more pressure on nature than ever before, but it’s also people who have the power to change this trajectory. Together, we can address the greatest threats to life on this planet and protect the natural resources that sustain and inspire us.
            Our goal - Recognizing that the problems facing our planet are increasingly more complex and urgent, WWF focuses its work on six ambitious goals. Through this integrative approach, we can challenge the planet’s greatest threats and ensure a healthy future for people and nature."<br><br>
            Website: https://www.worldwildlife.org<br><br>
            National Wildlife Federation: "The National Wildlife Federation, America's largest and most trusted conservation organization, works across the country to unite Americans from all walks of life in giving wildlife a voice. We've been on the front lines for wildlife since 1936, fighting for the conservation values that are woven into the fabric of our nation's collective heritage.
            Our strategic plan sets in motion a Common Agenda for Wildlife to increase America's fish and wildlife populations and enhance their capability to thrive in a rapidly changing world."<br><br>
            Websites: https://www.nwf.org
        </div>
    </div>
    <footer class="site-footer">
        <div class="container">
            <p>Sriramteja Veerisetti - Deep Learning Applications</p>
        </div>
    </footer>
</body>
</html>

app/templates/results.html
<!-- app/templates/results.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detection Results</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script type="text/javascript">
        function fetchAnimalInfo(animalName) {
            // Here we create JavaScript code to fetch animal information
            document.getElementById('animal-info').innerHTML = '<div class="loader"></div>';
            fetch('/get-animal-info', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ animal_name: animalName }),
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('animal-info').innerHTML = data.info;
            })
            .catch(error => {
                document.getElementById('animal-info').textContent = 'Error fetching animal info.';
                console.error('Error fetching animal info:', error);
            });
        }
    </script>
</head>

<header class="header-background">
    <div class="container">
        <h1>Results!</h1>
    </div>
</header>
<body>
    <h1>These Are The Detected Animals Within Your Image!</h1>
    <h1>Please click on one of the detected animals to learn more about it!</h1>
    {% if detected_classes %}
        <ul id="animal-list">
            {% for animal in detected_classes %}
                <li onclick="fetchAnimalInfo('{{ animal }}')" class="animal-name">{{ animal }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No animals detected.</p>
    {% endif %}
    <p><a href="{{ url_for('main.home') }}">Upload another image</a></p>

    <div class="flex-container">
        <div class="info-sandbox">
            <div class="image-container">
                <img src="{{ image_url }}" alt="Processed Image">
            </div>
            <div class="text-container">
                <div id="animal-info" class="info-content"></div>
            </div>
        </div>
    </div>
    
</body>

<div id="chat-container">
    <button onclick="toggleChat()" id="chat-minimize">-</button>
    <div id="chat-content">
        <div id="chat-messages"></div>
        <div class="chat-input-container">
            <input type="text" id="chat-input" placeholder="Ask the chatbot a question">
            <button onclick="sendChatMessage()">Send</button>
        </div>
    </div>
</div>

<script>
    // Here we create JavaScript code to handle the chatbot functionality
    function sendChatMessage() {
        var input = document.getElementById('chat-input');
        var message = input.value;
        input.value = ''; 

        if(message.trim() !== '') {
            updateChatMessages('You', message);

            fetch('/chat', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({ message: message })
            })
            .then(response => response.json())
            .then(data => {
                updateChatMessages('Chatbot', data.message);
            })
            .catch(error => console.error('Error:', error));
        }
    }

    function updateChatMessages(sender, message) {
        var chatMessages = document.getElementById('chat-messages');
        var messageDiv = document.createElement('div');
        var messageContent = document.createTextNode(message); 
        var senderLabel = document.createTextNode(sender + ': '); 
        messageDiv.appendChild(senderLabel); 
        messageDiv.appendChild(messageContent); 
        if (sender === 'You') {
            messageDiv.classList.add('user');
        } else {
           messageDiv.classList.add('chatbot');
        }
        chatMessages.appendChild(messageDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight; 
    }

    function toggleChat() {
        var chatContent = document.getElementById('chat-content');
        var chatButton = document.getElementById('chat-minimize');
        if (chatContent.style.display === 'none') {
            chatContent.style.display = 'flex';
            chatButton.textContent = '-';
        } else {
            chatContent.style.display = 'none';
            chatButton.textContent = '+';
        }
    }

</script>
<style>
   #chat-container {
    position: fixed;
    bottom: 20px;
    right: 20px;
    width: 800px;
    background-color: white;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    z-index: 1000;
}

#chat-messages {
    height: 200px; 
    overflow-y: auto;
    padding: 15px; 
    border-bottom: 1px solid #ccc;
    font-size: 16px; 
}

#chat-input {
    width: calc(100% - 100px); 
    padding: 15px; 
    border: none;
    border-top: 1px solid #ccc;
    margin: 0;
    font-size: 16px; 
}

#chat-container button {
    width: 80px; 
    height: 52px; 
    border: none;
    background-color: #007bff;
    color: white;
    cursor: pointer;
    font-size: 16px; 
}

#chat-container button:hover {
    background-color: #0056b3;
}

#chat-messages div {
    padding: 10px; 
    border-radius: 10px; 
    margin-bottom: 10px; 
    max-width: 70%; 
    word-wrap: break-word; 
}
#chat-messages div.user {
    background-color: #e7e7e7; 
    align-self: flex-start; 
    margin-right: auto; 
}
#chat-messages div.chatbot {
    background-color: #d1edff; 
    align-self: flex-end; 
    margin-left: auto; 
}
#chat-container {
    display: flex;
    flex-direction: column;
    align-items: flex-end; 
    position: fixed;
    bottom: 20px;
    right: 20px;
    width: 800px;
}
#chat-messages {
    display: flex;
    flex-direction: column;
    height: 300px; 
}

#chat-container {
    display: flex;
    flex-direction: column;
    align-items: stretch; 
}

#chat-minimize {
    background-color: #ddd;
    border: none;
    cursor: pointer;
    padding: 5px 10px;
    font-size: 16px;
    align-self: flex-end;
    width: 100%;
    }

#chat-content {
    display: flex;
    flex-direction: column;
    width: 100%; 
}

chat-messages {
    overflow-y: auto;
    flex-grow: 0; 
}

#chat-input, #chat-container button {
    flex: none; 
}

.chat-input-container {
    display: flex;
    justify-content: space-between; 
    width: 100%; 
}

#chat-input {
    padding: 0; 
    border: none; 
}

#chat-container button {
    margin: 0; 
}

#chat-messages div.user,
#chat-messages div.chatbot {
    font-size: 22px; 
}

#chat-input {
    width: calc(100% - 100px);
    padding: 15px; 
    border: none;
    border-top: 1px solid #ccc;
    margin: 0;
    font-size: 25px; 
}
</style>
</html>